### ISSUE TITLE
Why regress joints after posing?

### ISSUE THREAD

**Issue by sebftw** [CalciferZh/SMPL#19]
I noticed we regress the joints twice in the scripts smpl_torch_batch.py and SMIL_torch_batch.py, and I was wondering about the correctness of this.

In the [SMPL paper](http://files.is.tue.mpg.de/black/papers/SMPL2015.pdf), it seems they define the joint positions as a regression on the rest pose, without pose blend shapes. We regress the final joint positions from the posed vertices with pose blend shapes.

In case this is an error, it can be fixed in [SMIL_torch_batch.py](https://github.com/CalciferZh/SMPL/blob/master/SMIL_torch_batch.py) by e.g. adding after line 190:
` Jtr = G[..., :4, 3] `
And then just deleting line 200, where we regress the joints a second time.
The difference is negligible, but it may be significant if you are doing 3D pose estimation. I saw a difference of at most 4 mm for the infant model, so I would estimate a worst-case error of 4 cm for the SMPL dataset.

**Comment by CalciferZh** [comment]
I agree that joint positions should be regressed from the rest pose. Since you are the author of [`SMIL_torch_batch.py`](https://github.com/CalciferZh/SMPL/blob/master/SMIL_torch_batch.py), feel free to make a PR. @Lotayou would you have time to check [`smpl_torch_batch.py`](https://github.com/CalciferZh/SMPL/blob/master/smpl_torch_batch.py)?

**Comment by Lotayou** [comment]
@CalciferZh I agree with you but don’t think a PR is necessary. One can simply switch on the `simplify` flag in the forward function. This way the pose blend shapes will not be performed and the estimated joint positions will be accurate.
