### ISSUE TITLE
Remove transformation of rest pose

### ISSUE THREAD

**Issue by quanhua92** [CalciferZh/SMPL#32]
Hi,
I can't understand the mathematical reason for the "remove the transformation due to the rest pose". Can you give me some hints? I know that it is the equation (3) in the paper. But I can't explain why it is implemented like this.
Thank you very much.

https://github.com/CalciferZh/SMPL/blob/f7a2eb30edfb99eb977c5dccdfcde25344a7f545/smpl_np.py#L109-L115

**Comment by CalciferZh** [comment]
Hi, I think "remove the transformation due to the rest pose" is a bad description. I should fix it.
Basically it's computing the vector from the joint to the vertex, so the rotation of that joint can be applied to that vector to calculate the vertex's location after posing.
You can also check the concept "linear blend skinning" for a better understanding.
